version: "3.7"

services:
  log-api:
    image: diamol/ch09-access-log
    networks:
      - app-net

  nasa-api:
    image: diamol/ch09-image-of-the-day
    ports:
      - 8088:80
    networks:
      - app-net
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.50"
          memory: 500M

  web-api:
    image: diamol/ch09-image-gallery
    ports:
      - 80:80
    networks:
      - app-net
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.50"
          memory: 500M

networks:
  app-net:
    name: home-net