services:
  todo-web:
    ports:
      - "8080:80"
    environment:
      - Database:Provider=Postgres
    networks:
      - app-net

  todo-db:
    image: diamol/postgres:11.5
    ports:
      - "5432:5432"
    networks:
      - app-net

networks:
  app-net:
    name: todo-test